name: Get Flag
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: fd800f43-0216-48ec-af5b-89d197325c45
          tenant-id: azure.training.hacktricks.xyz
          subscription-id: 9a025095-e37b-4d95-99d7-40ef2b122663
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage account list
          az storage blob download \
            --account-name iamazurelab374236b85 \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
